### PR TITLE
Add kubectl guide

### PR DESCRIPTION
**Pull request by alvaro-chalar**
Why:

* To provide kubectl clusters, users and contexts config information

### CODE REVIEW

**Review by vitaliiprodan — COMMENTED** [review]
Looks good however I'm not sure we are going to use that on other projects. @tom-mullen should we keep information regarding services/tools which is not common used at DVELP?

**Comment by vitaliiprodan** [comment]
If so, probably it's worth to introduce some common commands like `delete pod`, `exec`, etc

**Comment by alvaro-chalar** [comment]
> If so, probably it's worth to introduce some common commands like `delete pod`, `exec`, etc

Sure, that wouldn't be a problem.

**Comment by tom-mullen** [comment]
@alvaro-chalar we are likely to be moving all our code/apps to Kubernetes in the near future. So might be worth building a template app/config deployment setup here.  cc/ @vitaliiprodan @Ammet

**Pull request closed without merging**
